#!/usr/bin/with-contenv bash
# shellcheck shell=bash

USER_DIRECTORY=(\
    "images" \
    "data" \
    )

## Make data directories
if [[ ! -d /config/mediawiki/data ]]; then
    mkdir -p /config/mediawiki/data
fi

if [[ ! -d /config/mediawiki/images ]]; then
    mkdir -p /config/mediawiki/images
fi

## Move user folders to persistent storage
for i in "${USER_DIRECTORY[@]}"; do
    if [[ ! -d /config/mediawiki/"${i}" ]] && [[ -d /app/www/public/"${i}" ]]; then
        mv /app/www/public/"${i}" /config/mediawiki/"${i}"/
    fi
done

## Remove user folders
for i in "${USER_DIRECTORY[@]}"; do
    if [[ -d /app/www/public/"${i}" ]]; then
        rm -rf /app/www/public/"${i}"
    fi
done

## Make Symlinks
for i in "${USER_DIRECTORY[@]}"; do
    if [[ ! -L /app/www/public/"${i}" ]]; then
        ln -s /config/mediawiki/"${i}" /app/www/public/"${i}"
    fi
    lsiown abc:abc /config/mediawiki/"${i}"
done

## Bump php upload max filesize and post max size to 10MB by default
if ! grep -qF 'upload_max_filesize' /config/php/php-local.ini; then
    echo 'upload_max_filesize = 10M' >> /config/php/php-local.ini
fi
if ! grep -qF 'post_max_size' /config/php/php-local.ini; then
    echo 'post_max_size = 10M' >> /config/php/php-local.ini
fi

## Remove mw-config.php once setup complete
if [[ -f /config/mediawiki/LocalSettings.php ]]; then
    if rm -rf /app/www/public/mw-config; then
        echo "Existing install found, deleting mw-config."
    fi
else
    echo "Go to http://IP-ADDRESS:PORT/mw-config/index.php to configure your install then restart your container when finished to remove mw-config"
fi

# permissions
lsiown -R abc:abc \
    /app/www/public/images \
    /app/www/public/data