<?php
# This file was automatically generated by the MediaWiki 1.36.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
        exit;
}
## The URL base path to the directory containing the wiki;
$wgScriptPath = "";
## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;
# emails
$wgEnableEmail = false;
$wgEnableUserEmail = false;
$wgEmailAuthentication = true;
# image uploads
$wgEnableUploads = true;
$wgUseImageMagick = true;
# pingback to wikidata
$wgPingback = true;
# cache
$wgUseFileCache = true;
$wgCacheDirectory = "/tmp";
$wgMainCacheType = CACHE_ACCEL;
# site language code
$wgLanguageCode = "en-ca";

# database auth and settings
require_once "/secrets/mysql.php";
# secretKey, authenticationTokenVersion, upgradeKey
require_once "/secrets/keys.php";
# site name and logos
require_once "/includes/Branding.php";

require_once "/includes/License.php";
require_once "/includes/Skins.php";
require_once "/includes/Extensions.php";
require_once "/includes/Permissions.php";

# End of automatically generated settings.
# Add more configuration options below.

$wgArticlePath = "/w/$1";

require_once "/includes/Namespaces.php";